changelog.md, controllers/front/notify.php, saferpayofficial.php
$order was being set before Assert action which made changes to the same order.
By using same $order later on to capture payments it caused it to override Assert action changes.
=> SL-59 Increased module version, fixed order overriding data

src/Config/SaferPayConfig.php, tests/Unit/Service/PaymentRestrictionValidation/KlarnaPaymentRestrictionValidationTest.php
T "IT" and "FR" added to KLARNA_SUPPORTED_COUNTRY_CODES. Assertions  for 'IT' and 'FR' added into into test KlarnaPaymentRestrictionValidationTest.php
=> IT and FR added to list of supported countries

config/service.yml, src/Provider/PaymentRestrictionProvider.php, src/Provider/PaymentRestrictionProviderInterface.php, src/Service/PaymentRestrictionValidation.php
Issue: Managed to replicate the issue on newly installed PS and the latest saferPay version.
The issue is on PS from 1.7.1 to 1.7.4. It seems to be working with 1.6 and works from 1.7.5.
Since lower PS versions do not support Symfony 3.4  method to register services in arguments with !tagged i needed to register them in the old fashion way because !tagged [services] were given just as a string. 
- Changed var type since now we are getting array not traversible
- Changed the way services are passed to the argument
=> PS 1.7.1 compability fixes with sympfony

controllers/front/hostedIframe.php
In PS 1.78~ version and above checkout/_partials/footer.tpl template starts to use tos_cms variable for Terms and Conditions which comes from OrderController but since our form is hosted iframe we are out of this scope and we lose this variable. Implemented the same function in our controller to get tos_cms variable.
=> tos_cms variable fix on PS1.78~ versions and above

controllers/front/successIFrame.php
The problem was with credit card savings. There was an error in custumer_id it took from context which was null and it failed to fetch the saved card from DB. Previously it took from context but since Iframe go outside of context and scope customer ID was null. Small fix changed took customer id from order
Fix
=> Credit card saving fix.

src/Provider/PaymentRestrictionProvider.php, src/Provider/PaymentRestrictionProviderInterface.php
Forgot that this module must to compatible with older PHP and PS versions. Changed retrun type declaration.
=> Changed return type declaration for compatability

src/Config/SaferPayConfig.php
LastSchrift and MasterCard payment validation were failing due to wrong data sent to the backend. After communication with the integration team fixes were applied for LastSchrift and Mastercard payments
=> MasterCard and Lastschrift payment fixes

config/service.yml, controllers/admin/AdminSaferPayOfficialPaymentController.php, saferpayofficial.php, src/Service/SaferPayObtainPaymentMethods.php, src/Service/SaferPayPaymentNotation.php, tests/Unit/Service/SaferPayPaymentNotationTest.php
After SaferPay's official statement that BackEnd fixes with payment notations will be only in October and only in the newest version, they asked to adopt the module for wrong payment notations from the backend. One of the examples Diner Club payment, from the Safer backend we getting Diners Club but our constant is DINERS and these constants are approved by SaferPay. I created a small function witch adapts payment method notations on saved cards because this place was affected. Card saving now working as intended
=> Payment notation fix from SaferPayAPI

changelog.md, controllers/admin/AdminSaferPayOfficialSettingsController.php, controllers/front/iframe.php, controllers/front/notify.php, controllers/front/successHosted.php, controllers/front/successIFrame.php, saferpayofficial.php, src/Config/SaferPayConfig.php, src/Service/SaferPay3DSecureService.php, src/Service/SaferPayInitialize.php, src/Service/SaferPayOrderStatusService.php, src/Service/TransactionFlow/SaferPayTransactionAuthorization.php
Fixed issue when payment was cancelled due to 3DS failure but Order confirmation was still shown, changed it to order page step 1.
Fixed issue when 3DS failed but it still captured/authorized payment based on settings prior to canceling.
=> SL-133 checkout issues

changelog.md, src/Service/SaferPayPaymentNotation.php
Adding different name as MAESTRO is available while MAESTRO-INTL. is not.
=> SL-142/maestro payment method notation

changelog.md, controllers/front/failValidation.php, saferpayofficial.php, src/Adapter/LegacyContext.php, src/Service/PaymentRestrictionValidation/ApplePayPaymentRestrictionValidation.php
https://invertus.atlassian.net/browse/SL-160
Applay Pay option was not displayed in the payment methods tab for macintosh pc's because validation only checked if it was an iOS device.
=> SL-160/bug/payment-applepay

src/DTO/Request/Initialize/InitializeRequest.php, src/Service/Request/InitializeRequestObjectCreator.php, src/Service/SaferPayInitialize.php
Task: https://invertus.atlassian.net/browse/SL-176
Branch: SL-176 from master
Changes:
- added functionality to unset Notification Container from API Request for endpoint `Payment/v1/Transaction/Initialize` (related to `isBusinessLicense`) and for SaferPay API version lower than 1.35
For isBusinessLicense = 1 (Notification container is unset):
For isBusinessLicense = 0 (Notification container is present):
=> SL-176: unset notification container for previous API version

controllers/front/notify.php, controllers/front/return.php, controllers/front/success.php, src/Service/TransactionFlow/SaferPayTransactionAssertion.php
These changes fix the redirect issue when payment is aborted.
=> SL-155/aborted-payment-issue

src/Api/Request/AssertService.php, src/DTO/Request/Assert/AssertRequest.php, src/Service/TransactionFlow/SaferPayTransactionAssertion.php
Fixed an error on checkout with an transaction type payment method on hosted/iframe method.
Since the initial front controller does an assertTransaction method so if it's a transaction it send a request to the authorize endpoint ;D and then on success controllers we call authorizeTransaction endpoint again and thus get an error.
A lot of refactoring is needed, but for now providing a solution for the issue.
=> SL-197: authorize error on iframe payment method

saferpayofficial.php, src/Install/Installer.php, src/Repository/SaferPayOrderRepository.php, upgrade/install-1.1.8.php
=> SL-196: payment method invoice append

src/Service/Request/InitializeRequestObjectCreator.php
Previously the LanguageCode was not being set, so the hosted iframe would always be set to default lang
=> SL-203: match shop language with iframe

src/Service/PaymentRestrictionValidation/ApplePayPaymentRestrictionValidation.php
removed strict type to allow 0 == false checking
tested on browser stack with safari.
=> SL-206: apple pay desktop

controllers/front/successIFrame.php, src/Api/ApiRequest.php, src/Api/Request/AssertService.php, src/Config/SaferPayConfig.php, src/DTO/Response/ThreeDs.php, src/Service/LegacyTranslator.php, src/Service/Request/InitializeRequestObjectCreator.php, src/Service/Response/ResponseObjectCreator.php, upgrade/install-1.1.8.php
Increased API version 1.32 => 1.37
main changes:
- Added/Removed payment/wallet values.
- Removed values from request containers
- Fixed front controller not redirecting to success page.
- Updated config values
=> SL-205: api version increase

controllers/front/notify.php, controllers/front/return.php
Setting to capture on authorization bug fix.
On successfull payment saferpay api reaching two endpoints. Notify and return. 
On notify controller found that orderId is not refreshed after order creation.
Added additional validation on return controller to check is saferpay already reached notify controller.
=> SL-204/ Default payment behavior on capture bug fix

controllers/front/notify.php, controllers/front/return.php, saferpayofficial.php, src/Core/Order/Verification/CanSendOrderConfirmationEmail.php, src/Install/Installer.php, src/Processor/CheckoutProcessor.php, upgrade/install-1.2.2.php
Order confirmation and new order mails was not working with setting "after authorization".
=> SL-212/email fix

.gitignore, composer.json, controllers/front/notify.php, controllers/front/return.php, src/Controller/AbstractSaferPayController.php, src/Response/Response.php, var/cache/index.php, var/index.php
=> SL-229/ Race condition fix

controllers/front/notify.php, controllers/front/pendingNotify.php, controllers/front/return.php, saferpayofficial.php, src/Config/SaferPayConfig.php, src/Core/Order/Action/UpdateOrderStatusAction.php, src/Processor/CheckoutProcessor.php, src/Repository/SaferPayOrderRepository.php, src/Service/SaferPayInitialize.php, src/Service/SaferPayOrderStatusService.php
https://invertus.atlassian.net/browse/SL-238
https://invertus.atlassian.net/browse/SL-239
=> Cleanup and fix payment authorization issues

controllers/front/ajax.php, controllers/front/notify.php, controllers/front/return.php, saferpayofficial.php, src/Controller/AbstractSaferPayController.php, src/Install/Installer.php, src/Processor/CheckoutProcessor.php, src/Service/SaferPayOrderStatusService.php, src/Service/TransactionFlow/SaferPayTransactionAssertion.php
related issues https://invertus.atlassian.net/browse/SV-15
https://invertus.atlassian.net/browse/SL-240
Move ajax getStatus action to dedicated controller;
Allow asserting transaction without updating saferpayOrder (which was the main cause causing the loop, because during getStatus it used to mess up saferPayOrder values).
This seems to prevent endless loop when waiting for return.
=> [SL-240,SV-15] Fix infinite loop after payment

controllers/front/return.php, controllers/front/successIFrame.php, src/Api/Request/AssertService.php, src/DTO/Request/Assert/AssertRequest.php, src/Service/Request/AssertRequestObjectCreator.php, src/Service/TransactionFlow/SaferPayTransactionAssertion.php, src/ServiceProvider/BaseServiceProvider.php, views/js/front/hosted-templates/hosted_fields.js, views/templates/front/credit_cards.tpl, views/templates/front/credit_cards_16.tpl
* Now when using saved credit card, user will be redirected to new page (instead of iframe)
* Fixed credit card saving
=> SL-219 Fixed credit card saving

controllers/front/return.php
Added method to assert correct fail controller
=> Fail controller recognition 

controllers/admin/AdminSaferPayOfficialSettingsController.php, controllers/front/successIFrame.php, saferpayofficial.php, src/Validation/CustomerCreditCardValidation.php, views/js/front/saferpay_iframe_16.js
* Fixed Iframe redirect
* OFF credit card saving on PS16
*
=> SL-264 Prestashop 1.6 Problems

controllers/admin/AdminSaferPayOfficialPaymentController.php
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Release branch?           | [release-v1.2.5](https://github.com/Invertus/saferpayofficial/tree/release-v1.2.5)
| Description?      | Improved performance / loading speed on Back Office SaferPay "Payments" tab. 
| Type?             | Improvement / Performance
| PrestaShop side (FO/BO/BOTH)         | BO
| Deprecations?     | No
| How to test?      | Enable PrestaShop profiler and go to SaferPay -> Payments. Scroll down and see "Load time"
| Which issue fixed? Assigned ticket on Jira    | [SL-270](https://invertus.atlassian.net/browse/SL-270)
| Related PRs (similar)       | #192 - Performance FO in checkout
Screenshots (if available):
[SL-270]: …
=> SL-270 Performance issues in BO "Payments" tab

saferpayofficial.php, src/Config/SaferPayConfig.php, src/Service/LegacyTranslator.php, src/Service/SaferPayObtainPaymentMethods.php
Reverts Invertus/saferpayofficial#228
=> Revert "SL-271 New payment methods integration"

changelog.md, views/js/front/hosted-templates/hosted_fields.js, views/js/front/opc/onepagecheckoutps/hosted_fields.js
Wrote return statement for logic when not saferpay payment method is selected to stop executing code. Also tested with OPC modules and copied logic to work properly with one of OPC modules which also have that issue.
=> BUGFIX Wrong payment method logic executing
