src/Service/Request/InitializeRequestObjectCreator.php, src/Service/SaferPayOrderStatusService.php
=> Added rounding of prices

controllers/front/hostedIframe.php
Left mistake to call getDefaultTermsAndConditions function below 177 version
=> tos onnly above version 177

src/Service/SaferPayOrderStatusService.php
Problem accrued in order saferpay tab after trying to partial refund no order status was changed. Added logic to change order status and update order.
=> SL-119 Partly refunded order status

saferpayofficial.php, src/Service/SaferPayPaymentNotation.php
One payment notation fix was missing, and fixed card saving namings in checkout.
=> Fixed one missing payment notation, correction for card saving namings

src/Service/SaferPayPaymentNotation.php
PHP compatibility issue. Module was not tested locally on 5.6.
=> SL-125: Module BO settings payment tab error fix

saferpayofficial.php, src/Provider/PaymentRedirectionProvider.php, src/Service/SaferPayPaymentNotation.php
If has business license - show display hosted field form, otherwise - not.
=> SL-125 businnes license hosted field

changelog.md, config/config.yml, config/service.yml, controllers/front/ajax.php, controllers/front/hostedIframe.php, saferpayofficial.php, src/Enum/ControllerName.php, src/Enum/PaymentType.php, src/Presentation/Loader/PaymentFormAssetLoader.php, src/Provider/PaymentRedirectionProvider.php, src/Provider/PaymentTypeProvider.php, src/Service/SaferPayInitialize.php, views/js/front/hosted-templates/hosted_fields.js, views/js/front/hosted-templates/hosted_fields_16.js, views/js/front/saferpay_saved_card_16.js, views/templates/front/hosted-templates/template1.tpl, views/templates/front/hosted-templates/template1_16.tpl, views/templates/front/hosted-templates/template2.tpl, views/templates/front/hosted-templates/template2_16.tpl, views/templates/front/hosted-templates/template3.tpl, views/templates/front/hosted-templates/template3_16.tpl, views/templates/hook/front/payment_with_cards.tpl
With hosted fields there was no way to actually save credit cards, implemented it for PS 1.7 and PS 1.6.
=> SL-123 credit card saving with hosted fields

views/js/front/hosted-templates/template1.js, views/js/front/hosted-templates/template2.js, views/js/front/hosted-templates/template3.js, views/js/front/hosted-templates/template_submit.js
Missed getElementById when changing 'submit' id to 'submit_hosted_field'
=> SL-123 hosted fields submit button enabling

src/Service/TransactionFlow/SaferPayTransactionAuthorization.php
Context seems to be missing due to iframe :]
=> SL-133 iframe saving card fix

changelog.md, saferpayofficial.php, src/Service/PaymentRestrictionValidation/BasePaymentRestrictionValidation.php, src/Service/SaferPayPaymentNotation.php
Seems like previous PR changed it to be ISO from API, but broke previous ID logic
=> SL-141/payment-options

composer.json, config/config.yml, config/repository.yml, config/service.yml, src/Api/ApiRequest.php, src/Api/Request/InitializeService.php, src/Api/Request/ObtainPaymentMethodsService.php, src/DTO/Request/ObtainPaymentMethods/ObtainPaymentMethodsRequest.php
https://invertus.atlassian.net/browse/SL-157
Installed new apimatic/unirest-php api library, removed old one.
Rewrote API request get,post methods using unirest syntax.
=> SL-157/fix/unirest-php-requests

controllers/front/validation.php
=> fixed duplicated code

controllers/front/ajax.php, controllers/front/return.php, src/Config/SaferPayConfig.php, src/DTO/Request/Initialize/InitializeRequest.php, src/DTO/Request/ObtainPaymentMethods/ObtainPaymentMethodsRequest.php, src/DTO/Request/ReturnUrl.php, src/Enum/ControllerName.php, src/Service/Request/InitializeRequestObjectCreator.php, src/Service/Request/RequestObjectCreator.php, src/Service/SaferPayInitialize.php
Module API version increase 1.25 => 1.32
=> SL-155/api-version-change

controllers/front/success.php
Task: https://invertus.atlassian.net/browse/SL-176
Branch: SL-176 from master
Changes:
- excluding the assertion from the success.php controller now to fix this bug
=> SL-176/duplicated-order-statuses

src/Service/Request/RequestObjectCreator.php
Moved description setting earlier as it is required
=> SL-210/description required fix

src/Processor/CheckoutProcessor.php
On certain settings transaction status is missing, this causes order management does not appear in admin page.
=> SL-209/ Missing authorized status

saferpayofficial.php, src/Install/Installer.php, upgrade/install-1.2.2.php
The ordering of the hooks was incorrect. MailSendBefore hook did not had updated order status
=> SL-212/ Mail send fix

controllers/front/notify.php, src/Controller/AbstractSaferPayController.php
Was hard to solve conflicts so I copied changes manually, it was easier to understand this way
=>  apply changes from branch SL-232/conflicting-calls.

src/Config/SaferPayConfig.php, src/DTO/Request/Initialize/InitializeRequest.php
Now it will require customer to enter his full name when entering card details. Everything else Safer handles
[Issue](https://invertus.atlassian.net/browse/SL-257)
=> SL-257 Added 'Holder Name' into BO

controllers/admin/AdminSaferPayOfficialSettingsController.php, src/Config/SaferPayConfig.php
=> SV-35 Added "Debug mode" option

saferpayofficial.php, src/Repository/SaferPayPaymentRepository.php, src/Service/PaymentRestrictionValidation/BasePaymentRestrictionValidation.php
* Optimized SQL querys 320 -> 278
* Optimized API requests 17 -> 1-2
Before:
After:
=> SL-244 performance issues in checkout

saferpayofficial.php, src/Service/SaferPayOrderStatusService.php, views/templates/front/credit_cards.tpl, views/templates/front/credit_cards_16.tpl
Also fixed not rendering credit cards.
=> SL-234 Ability to override our My Account template

controllers/front/return.php, src/Service/SaferPayInitialize.php
Added paymentMethod into return URL to get current payment method when order isnt created
=> Iframe fail redirection adjustments

src/Presentation/Loader/PaymentFormAssetLoader.php
[Issue](https://invertus.atlassian.net/browse/SL-262)
=> SL-262 PS1.6 css images sizes

saferpayofficial.php
Now showing payment options based on their supported currencies
=> SL-265 Payment currencies detection on Prestashop 1.6

views/js/front/hosted-templates/hosted_fields.js
Updated javascript logic to recognize is submitted field from saferpay or from other payment method
=> SL-269 Updates javascript for other payment methods interruption

.github/PULL_REQUEST_TEMPLATE.yml, .github/workflows/PULL_REQUEST_LABELS.yml, .github/workflows/PULL_REQUEST_NAMING_RULES.yml
Updated workflow and PR template
=> INTERNAL update workflow & template

.github/workflows/deploy.yml
=> INTERNAL workflow fix

controllers/admin/AdminSaferPayOfficialPaymentController.php
In earlier versions when obtaining payment methods and foreaching them all wallets gets latest payment method currencies.
=> SL-277 wallet undefined currencies bugfix

saferpayofficial.php
Fixed issue where payment options aren't displayed because of silenced fatal error
=> SL-270 Fixed wallets breaking payment options

saferpayofficial.php
=> INTERNAL version bump

changelog.md
=> INTERNAL updated changelog

src/Adapter/Cart.php, src/Context/index.php, src/Controller/AbstractAdminSaferPayController.php, src/EntityManager/index.php, src/Logger/Formatter/index.php, src/Logger/Logger.php, src/Logger/index.php, views/js/front/opc/onepagecheckoutps/index.php, views/js/front/opc/supercheckout/index.php, views/js/front/opc/thecheckout/index.php, views/templates/admin/logs/index.php
=> INTERNAL validator fix

upgrade/install-1.2.5.php
Updated version API in database, not only in Configuration class.
=> SL-278 Upgraded header API version

.github/PULL_REQUEST_TEMPLATE.yml
=> INTERNAL update pr template

.github/workflows/create_zip.yml, .github/workflows/deploy.yml, .github/workflows/release.yml
=> INTERNAL create zip creation action

.github/workflows/create_zip.yml, .github/workflows/deploy.yml, .github/workflows/release.yml
Deleting necessary development files on zip creation
=> INTERNAL delete development files on zip creation

saferpayofficial.php
=> SL-283 capture error

changelog.md
=> INTERNAL changelog 1.2.6

saferpayofficial.php
Minor issues fixed with wrong namespaces
=> BUGFIX namespace error in main file & optimization

controllers/admin/AdminSaferPayOfficialSettingsController.php
[SL-284](https://invertus.atlassian.net/browse/SL-284)
Fixed notice errors and divided all configurations page into separate methods for better readability and usability
[SL-284]: https://invertus.atlassian.net/browse/SL-284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SL-284 Fixed saved cards notice

saferpayofficial.php, src/Provider/CurrencyProvider.php
[SL-286](https://invertus.atlassian.net/browse/SL-286)
Wallet payment methods doesn't come with available currencies because it supports all currencies, so we add all currencies before validating
[SL-286]: https://invertus.atlassian.net/browse/SL-286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SL-286 notice fix & added currency provider | PS 1.6

changelog.md, src/Config/SaferPayConfig.php, src/Install/Installer.php
[SL-285](https://invertus.atlassian.net/browse/SL-285)
Order status isnt existing when setting it to its ID. So moved configuration installed after order status creation
[SL-285]: https://invertus.atlassian.net/browse/SL-285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SL-285 fix default awaiting order state

changelog.md, saferpayofficial.php, src/Config/SaferPayConfig.php, src/Install/Installer.php
https://invertus.atlassian.net/browse/SL-250
Fix for "duplicate entry" SQL error on module install
=> SL-250 Duplicate entry PrestaShop on module install fix

src/Config/SaferPayConfig.php, src/Service/LegacyTranslator.php
=> SL-299 api bump 1.45

controllers/front/return.php
=> SL-296 redirection fix

changelog.md, src/Repository/SaferPayOrderRepository.php
https://invertus.atlassian.net/browse/SL-298
Made that SQL query will get latest id_saferpay_order instead of random one (which most of time will be not latest)
Try various checkouts
=> SL-298 invalid token on authorization

controllers/front/return.php
=> SL-301 minor bug fixes

.github/workflows/release.yml
https://invertus.atlassian.net/browse/SL-303
Fixed release action to create zip on release
=> SL-303 fix release action

src/Config/SaferPayConfig.php
=> SL-310 installation error

changelog.md, saferpayofficial.php
=> SL-314 Issue when live credentials to redirect to payments page

changelog.md, src/Service/PaymentRestrictionValidation/BasePaymentRestrictionValidation.php
https://invertus.atlassian.net/browse/SL-317
Enhanced payments restirction showing validator
- Added payment method enabled status check before country/currency validation
- Added currency restrictions validation
- Improved validation logic for country and currency restrictions
=> SL-317: Fix disabled payment method visibility

changelog.md, src/Install/Installer.php
https://invertus.atlassian.net/browse/SL-316
Now it sends email after authorization, not after capture
=> SL-316 fix email sending on successful order

changelog.md, src/Install/Installer.php
Reverts Invertus/saferpayofficial#274
=> Revert "SL-316 fix email sending on successful order"

saferpayofficial.php
=> INTERNAL change version

controllers/admin/AdminSaferPayOfficialLogsController.php
=> SL-324 logs syntax

src/Config/SaferPayConfig.php, upgrade/install-2.0.2.php
=> INTERNAL grouping release fixes

saferpayofficial.php, src/Service/SaferPayObtainPaymentMethods.php
=> INTERNAL cleanup

README.md
=> INTERNAL update readme

MAINTAINERS.md
=> SL-326 maintainers guide
